version: "3.6"

services:
  vault:
    image: vault
    container_name: vault-server
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/file:/vault/file
      - ./vault/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server
    cap_add:
      - IPC_LOCK
